package cn.mark.network.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    /** Not-null value. */
    private String username;
    private String nickname;
    private String image;
    private String phone;
    private String token;
    private String email;
    private String taobao_phone;
    private Boolean isLogin;
    private Integer user_id;
    private Integer phone_verify;
    private Integer taobao_phone_verify;
    private Long id;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(String username, String nickname, String image, String phone, String token, String email, String taobao_phone, Boolean isLogin, Integer user_id, Integer phone_verify, Integer taobao_phone_verify, Long id) {
        this.username = username;
        this.nickname = nickname;
        this.image = image;
        this.phone = phone;
        this.token = token;
        this.email = email;
        this.taobao_phone = taobao_phone;
        this.isLogin = isLogin;
        this.user_id = user_id;
        this.phone_verify = phone_verify;
        this.taobao_phone_verify = taobao_phone_verify;
        this.id = id;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTaobao_phone() {
        return taobao_phone;
    }

    public void setTaobao_phone(String taobao_phone) {
        this.taobao_phone = taobao_phone;
    }

    public Boolean getIsLogin() {
        return isLogin;
    }

    public void setIsLogin(Boolean isLogin) {
        this.isLogin = isLogin;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public Integer getPhone_verify() {
        return phone_verify;
    }

    public void setPhone_verify(Integer phone_verify) {
        this.phone_verify = phone_verify;
    }

    public Integer getTaobao_phone_verify() {
        return taobao_phone_verify;
    }

    public void setTaobao_phone_verify(Integer taobao_phone_verify) {
        this.taobao_phone_verify = taobao_phone_verify;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
